import json
import os
from typing import Literal, Optional, cast

import pandas as pd
from fastapi import APIRouter, Depends, Query
from pydantic import BaseModel

from backend.app.api.schemas import context_filters
from backend.app.core.errors import ERROR_RESPONSES, AppError
from backend.app.core.security import require_agronomist, require_user
from backend.app.services import dataset, insights
from backend.app.services.dataset import Filters

router = APIRouter(prefix="/api/analytics", tags=["Analytics"], responses=ERROR_RESPONSES)

EDA_METRICS_PATH = os.path.join("datasets", "processed", "eda_summary_metrics.json")


class CropBreakdown(BaseModel):
    count: int
    avg_yield: float
    std_yield: Optional[float] = None
    min_yield: Optional[float] = None
    max_yield: Optional[float] = None


class EdaMetrics(BaseModel):
    total_records: int
    overall_stats: dict[str, dict[str, float]]
    crop_breakdown: dict[str, CropBreakdown]
    top_crop_by_yield: Optional[str] = None


class RegionRank(BaseModel):
    region: str
    mean_yield_kg_ha: float
    median_yield_kg_ha: float
    record_count: int


class RegionRanking(BaseModel):
    scope: str
    global_mean_kg_ha: float
    total_regions: int
    regions: list[RegionRank]


class YearPoint(BaseModel):
    year: int
    mean_yield_kg_ha: float
    median_yield_kg_ha: float
    record_count: int


class Forecast(BaseModel):
    year: int
    mean_kg_ha: float
    p10_kg_ha: float
    p90_kg_ha: float
    basis_year: int
    basis_records: int
    method: str


class SeasonalTrends(BaseModel):
    granularity: Literal["year"]
    scope: str
    series: list[YearPoint]
    missing_years: list[int]
    forecast: Optional[Forecast]


class FarmRow(BaseModel):
    farm_id: str
    region: str
    crop_type: str
    year: int
    yield_kg_ha: float
    soil_health_index: float
    soil_pH: float
    soil_moisture_percent: float
    ndvi: float
    risk_rating: Literal["Low", "Medium", "High"]
    risk_flags: list[str]


class FarmComparison(BaseModel):
    scope: str
    total_records: int
    mean_yield_kg_ha: Optional[float]
    sort: str
    farms: list[FarmRow]
    risk_method: str


@router.get("/metrics", response_model=EdaMetrics)
def get_eda_metrics(_user: dict = Depends(require_user)):
    """EDA summary generated by scripts/run_eda.py."""
    if not os.path.exists(EDA_METRICS_PATH):
        raise AppError(404, "EDA summary metrics not found. Run scripts/run_eda.py.")
    with open(EDA_METRICS_PATH, "r", encoding="utf-8") as f:
        return json.load(f)


class HistogramBin(BaseModel):
    start: float
    end: float
    count: int


class ScatterPoint(BaseModel):
    x: float
    y: float


class Regression(BaseModel):
    """Least-squares fit. All fields are null when x has a single value (no relationship can be fitted)."""

    slope: Optional[float]
    intercept: Optional[float]
    r: Optional[float]
    r2: Optional[float]


class BinnedMean(BaseModel):
    start: float
    end: float
    mean_yield_kg_ha: float
    count: int


class EdaCharts(BaseModel):
    scope: str
    record_count: int
    yield_histogram: list[HistogramBin]
    yield_mean_kg_ha: float
    yield_median_kg_ha: float
    rainfall_vs_yield: list[ScatterPoint]
    rainfall_regression: Regression
    rainfall_distinct_values: int
    ph_bins: list[BinnedMean]
    ph_optimal_low: Optional[float]
    ph_optimal_high: Optional[float]


@router.get("/eda-charts", response_model=EdaCharts)
def get_eda_charts(
    f: Filters = Depends(context_filters),
    bins: int = Query(30, ge=5, le=100),
    sample: int = Query(400, ge=50, le=2000),
    _user: dict = Depends(require_agronomist),
):
    """Chart-ready EDA data computed from the dataset: yield histogram, rainfall-vs-yield sample
    with a least-squares fit (r and R² over all filtered records), and mean yield by pH bin."""
    import numpy as np

    from backend.app.core.agronomy_rules import rules_for

    df = dataset.filter_df(f)
    if df.empty:
        # An empty context is a valid answer (e.g. a crop a country doesn't grow), not an error.
        return {
            "scope": f.describe(), "record_count": 0, "yield_histogram": [], "yield_mean_kg_ha": 0.0, "yield_median_kg_ha": 0.0,
            "rainfall_vs_yield": [], "rainfall_regression": {"slope": None, "intercept": None, "r": None, "r2": None},
            "rainfall_distinct_values": 0, "ph_bins": [], "ph_optimal_low": None, "ph_optimal_high": None,
        }
    y = df["yield_kg_per_hectare"].to_numpy(dtype=float)
    counts, edges = np.histogram(y, bins=bins)
    rain = df["rainfall_mm"].to_numpy(dtype=float)
    # Rainfall is one long-term value per country, so a single-country context has nothing to fit.
    rain_values = int(np.unique(rain).size)
    if rain_values >= 2 and len(df) >= 3 and float(np.std(y)) > 0:
        slope, intercept = (float(v) for v in np.polyfit(rain, y, 1))
        r = round(float(np.corrcoef(rain, y)[0, 1]), 4)
        regression = {"slope": slope, "intercept": intercept, "r": r, "r2": round(r * r, 4)}
    else:
        regression = {"slope": None, "intercept": None, "r": None, "r2": None}
    pts = df.sample(min(sample, len(df)), random_state=42)
    ph_edges = np.round(np.arange(np.floor(df["soil_pH"].min() * 4) / 4, df["soil_pH"].max() + 0.25, 0.25), 2)
    ph_groups = df.groupby(pd.cut(df["soil_pH"], ph_edges, include_lowest=True), observed=True)["yield_kg_per_hectare"]
    crop_rules = rules_for(f.crop) if f.crop else None
    rng = crop_rules.optimal["soil_pH"] if crop_rules else None
    return {
        "scope": f.describe(),
        "record_count": int(len(df)),
        "yield_histogram": [
            {"start": round(float(edges[i]), 1), "end": round(float(edges[i + 1]), 1), "count": int(c)} for i, c in enumerate(counts)
        ],
        "yield_mean_kg_ha": round(float(y.mean()), 2),
        "yield_median_kg_ha": round(float(np.median(y)), 2),
        "rainfall_vs_yield": [{"x": float(a), "y": float(b)} for a, b in zip(pts["rainfall_mm"], pts["yield_kg_per_hectare"])],
        "rainfall_regression": regression,
        "rainfall_distinct_values": rain_values,
        "ph_bins": [
            {"start": float(iv.left), "end": float(iv.right), "mean_yield_kg_ha": round(float(g.mean()), 2), "count": len(g)}
            for iv, g in ((cast(pd.Interval, k), v) for k, v in ph_groups)
            if len(g) >= 5
        ],
        "ph_optimal_low": rng.low if rng else None,
        "ph_optimal_high": rng.high if rng else None,
    }


@router.get("/regions", response_model=RegionRanking)
def get_region_ranking(
    crop: Optional[str] = Query(None),
    limit: int = Query(10, ge=1, le=200),
    _user: dict = Depends(require_user),
):
    crop_name = dataset.canonical(crop, "crop_type") if crop else None
    if crop and not crop_name:
        raise AppError(404, f"Unknown crop '{crop}'.")
    ranking = dataset.region_ranking(crop_name)
    df = dataset.filter_df(Filters.of(crop=crop_name))
    return {
        "scope": f"{crop_name or 'All crops'} · mean yield by region",
        "global_mean_kg_ha": round(float(df["yield_kg_per_hectare"].mean()), 2),
        "total_regions": len(ranking),
        "regions": ranking[:limit],
    }


@router.get("/seasonal-trends", response_model=SeasonalTrends)
def get_seasonal_trends(f: Filters = Depends(context_filters), _user: dict = Depends(require_user)):
    """Yearly yield (sowing years 1990–2013) plus a model-based expectation with a P10–P90 band.
    All sowing dates in the dataset fall on 15 January, so month/season grouping is not possible."""
    if dataset.filter_df(f).empty:
        raise AppError(404, "No records match these filters.")
    return insights.seasonal_trends(f)


@router.get("/farm-comparison", response_model=FarmComparison)
def get_farm_comparison(
    f: Filters = Depends(context_filters),
    limit: int = Query(10, ge=1, le=100),
    sort: Literal["yield_desc", "yield_asc"] = Query("yield_desc"),
    _user: dict = Depends(require_user),
):
    return insights.farm_comparison(f, limit, sort)



class FarmSeasonPoint(BaseModel):
    year: int
    crop_type: str
    yield_kg_ha: Optional[float]
    reference_kg_ha: Optional[float]


class MyFarmComparison(BaseModel):
    farm_id: int
    name: str
    owner: str
    region: str
    area_ha: float
    seasons: int
    latest_year: Optional[int]
    latest_crop: Optional[str]
    latest_yield_kg_ha: Optional[float]
    mean_yield_kg_ha: Optional[float]
    reference_kg_ha: Optional[float]
    delta_pct: Optional[float]
    history: list[FarmSeasonPoint]


class MyFarmsResponse(BaseModel):
    farms: list[MyFarmComparison]
    method: str


@router.get("/my-farms", response_model=MyFarmsResponse)
def get_my_farm_comparison(user: dict = Depends(require_user)):
    """Real farms (yours; every farm for agronomists and admins) against the dataset's regional mean
    for the same crop and year (nearest dataset year when the season is newer than the data)."""
    from sqlalchemy import func, select

    from backend.app.core.security import is_privileged
    from backend.app.db.models import Farm, User
    from backend.app.db.session import session_scope

    df = dataset.get_df()
    ref = df.groupby(["region", "crop_type", "year"])["yield_kg_per_hectare"].mean()
    last_year = int(df["year"].max())

    def reference(region: str, crop: str, year: int) -> Optional[float]:
        y = min(year, last_year)
        for yy in (y, y - 1, y - 2):
            v = ref.get((region, crop, yy))
            if v is not None:
                return round(float(v), 2)
        return None

    out = []
    with session_scope() as s:
        q = select(Farm, User.username).join(User, User.id == Farm.owner_id)
        if not is_privileged(user):
            q = q.where(func.lower(User.username) == user["username"].lower())
        for farm, owner in s.execute(q.order_by(Farm.name).limit(100)).all():
            history = [
                {"year": r.year, "crop_type": r.crop_type, "yield_kg_ha": r.yield_kg_ha, "reference_kg_ha": reference(farm.region, r.crop_type, r.year)}
                for r in sorted(farm.records, key=lambda r: r.year)
            ]
            with_yield = [h for h in history if h["yield_kg_ha"] is not None]
            latest = with_yield[-1] if with_yield else None
            delta = None
            if latest and latest["reference_kg_ha"]:
                delta = round((latest["yield_kg_ha"] - latest["reference_kg_ha"]) / latest["reference_kg_ha"] * 100, 1)
            out.append(
                {
                    "farm_id": farm.id,
                    "name": farm.name,
                    "owner": owner,
                    "region": farm.region,
                    "area_ha": farm.area_ha,
                    "seasons": len(history),
                    "latest_year": latest["year"] if latest else None,
                    "latest_crop": latest["crop_type"] if latest else None,
                    "latest_yield_kg_ha": latest["yield_kg_ha"] if latest else None,
                    "mean_yield_kg_ha": round(sum(h["yield_kg_ha"] for h in with_yield) / len(with_yield), 2) if with_yield else None,
                    "reference_kg_ha": latest["reference_kg_ha"] if latest else None,
                    "delta_pct": delta,
                    "history": history,
                }
            )
    return {
        "farms": out,
        "method": f"Reference = dataset mean yield for the farm's region, crop and season year (the latest dataset year, {last_year}, for newer seasons).",
    }
