"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-30 14:16:57.840894
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('full_name', sa.String(length=80), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('hashed_password', sa.String(length=128), nullable=False),
    sa.Column('hash_scheme', sa.String(length=16), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('notification_prefs', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_users_username_lower', 'users', [sa.literal_column('lower(username)')], unique=True)
    op.create_table('audit_log',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('actor', sa.String(length=32), nullable=False),
    sa.Column('action', sa.String(length=40), nullable=False),
    sa.Column('target', sa.String(length=120), nullable=False),
    sa.Column('detail', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_created_at'), 'audit_log', ['created_at'], unique=False)
    op.create_table('crop_records',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('record_code', sa.String(length=32), nullable=False),
    sa.Column('region', sa.String(length=80), nullable=False),
    sa.Column('crop_type', sa.String(length=40), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('yield_kg_per_hectare', sa.Float(), nullable=False),
    sa.Column('rainfall_mm', sa.Float(), nullable=True),
    sa.Column('temperature_c', sa.Float(), nullable=True),
    sa.Column('pesticide_usage_ml', sa.Float(), nullable=True),
    sa.Column('soil_ph', sa.Float(), nullable=True),
    sa.Column('soil_moisture_percent', sa.Float(), nullable=True),
    sa.Column('humidity_percent', sa.Float(), nullable=True),
    sa.Column('sunlight_hours', sa.Float(), nullable=True),
    sa.Column('total_days', sa.Integer(), nullable=True),
    sa.Column('sowing_date', sa.Date(), nullable=True),
    sa.Column('harvest_date', sa.Date(), nullable=True),
    sa.Column('irrigation_type', sa.String(length=32), nullable=True),
    sa.Column('fertilizer_type', sa.String(length=40), nullable=True),
    sa.Column('crop_disease_status', sa.String(length=16), nullable=True),
    sa.Column('ndvi_index', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('upload_id', sa.String(length=32), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('record_code')
    )
    op.create_index('ix_crop_records_crop', 'crop_records', ['crop_type'], unique=False)
    op.create_index('ix_crop_records_region', 'crop_records', ['region'], unique=False)
    op.create_index('ix_crop_records_region_crop_year', 'crop_records', ['region', 'crop_type', 'year'], unique=False)
    op.create_index(op.f('ix_crop_records_upload_id'), 'crop_records', ['upload_id'], unique=False)
    op.create_index('ix_crop_records_year', 'crop_records', ['year'], unique=False)
    op.create_table('farms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('region', sa.String(length=80), nullable=False),
    sa.Column('area_ha', sa.Float(), nullable=False),
    sa.Column('crops', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('irrigation_type', sa.String(length=32), nullable=True),
    sa.Column('soil_ph', sa.Float(), nullable=True),
    sa.Column('soil_moisture_percent', sa.Float(), nullable=True),
    sa.Column('soil_type', sa.String(length=40), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_farms_owner_id'), 'farms', ['owner_id'], unique=False)
    op.create_index(op.f('ix_farms_region'), 'farms', ['region'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('severity', sa.String(length=12), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('link', sa.String(length=300), nullable=True),
    sa.Column('dedupe_key', sa.String(length=300), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'dedupe_key', name='uq_notification_dedupe')
    )
    op.create_index('ix_notifications_user_created', 'notifications', ['user_id', 'created_at'], unique=False)
    op.create_table('risk_levels',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('context_key', sa.String(length=200), nullable=False),
    sa.Column('risk_type', sa.String(length=20), nullable=False),
    sa.Column('level', sa.String(length=12), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'context_key', 'risk_type')
    )
    op.create_table('farm_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farm_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('crop_type', sa.String(length=40), nullable=False),
    sa.Column('area_ha', sa.Float(), nullable=False),
    sa.Column('yield_kg_ha', sa.Float(), nullable=True),
    sa.Column('rainfall_mm', sa.Float(), nullable=True),
    sa.Column('temperature_c', sa.Float(), nullable=True),
    sa.Column('pesticide_usage_ml', sa.Float(), nullable=True),
    sa.Column('fertilizer_type', sa.String(length=40), nullable=True),
    sa.Column('fertilizer_kg_ha', sa.Float(), nullable=True),
    sa.Column('irrigation_type', sa.String(length=32), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_farm_records_farm_id'), 'farm_records', ['farm_id'], unique=False)
    op.create_index('ix_farm_records_farm_year', 'farm_records', ['farm_id', 'year'], unique=False)
    op.create_table('predictions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('farm_id', sa.Integer(), nullable=True),
    sa.Column('record_code', sa.String(length=32), nullable=True),
    sa.Column('crop_type', sa.String(length=40), nullable=False),
    sa.Column('region', sa.String(length=80), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('inputs', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('predicted_yield_kg_ha', sa.Float(), nullable=False),
    sa.Column('low_kg_ha', sa.Float(), nullable=False),
    sa.Column('high_kg_ha', sa.Float(), nullable=False),
    sa.Column('productivity_rating', sa.String(length=8), nullable=False),
    sa.Column('risk_rating', sa.String(length=8), nullable=False),
    sa.Column('model_name', sa.String(length=80), nullable=False),
    sa.Column('model_version', sa.String(length=16), nullable=True),
    sa.Column('model_r2', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_predictions_farm_id'), 'predictions', ['farm_id'], unique=False)
    op.create_index(op.f('ix_predictions_record_code'), 'predictions', ['record_code'], unique=False)
    op.create_index('ix_predictions_user_created', 'predictions', ['user_id', 'created_at'], unique=False)
    op.create_table('recommendation_actions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('recommendation_id', sa.String(length=160), nullable=False),
    sa.Column('farm_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('region', sa.String(length=80), nullable=True),
    sa.Column('crop_type', sa.String(length=40), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('snooze_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('recommendation_id', 'user_id', name='uq_rec_action_user')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recommendation_actions')
    op.drop_index('ix_predictions_user_created', table_name='predictions')
    op.drop_index(op.f('ix_predictions_record_code'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_farm_id'), table_name='predictions')
    op.drop_table('predictions')
    op.drop_index('ix_farm_records_farm_year', table_name='farm_records')
    op.drop_index(op.f('ix_farm_records_farm_id'), table_name='farm_records')
    op.drop_table('farm_records')
    op.drop_table('risk_levels')
    op.drop_index('ix_notifications_user_created', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_farms_region'), table_name='farms')
    op.drop_index(op.f('ix_farms_owner_id'), table_name='farms')
    op.drop_table('farms')
    op.drop_index('ix_crop_records_year', table_name='crop_records')
    op.drop_index(op.f('ix_crop_records_upload_id'), table_name='crop_records')
    op.drop_index('ix_crop_records_region_crop_year', table_name='crop_records')
    op.drop_index('ix_crop_records_region', table_name='crop_records')
    op.drop_index('ix_crop_records_crop', table_name='crop_records')
    op.drop_table('crop_records')
    op.drop_index(op.f('ix_audit_log_created_at'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index('uq_users_username_lower', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
