"""weather observations

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-30 14:41:03.446182
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0002'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weather_observations',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('region', sa.String(length=80), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=True),
    sa.Column('rainfall_mm', sa.Float(), nullable=True),
    sa.Column('temperature_c', sa.Float(), nullable=True),
    sa.Column('humidity_percent', sa.Float(), nullable=True),
    sa.Column('sunlight_hours', sa.Float(), nullable=True),
    sa.Column('upload_id', sa.String(length=32), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_weather_obs_region_year', 'weather_observations', ['region', 'year'], unique=False)
    op.create_index(op.f('ix_weather_observations_upload_id'), 'weather_observations', ['upload_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weather_observations_upload_id'), table_name='weather_observations')
    op.drop_index('ix_weather_obs_region_year', table_name='weather_observations')
    op.drop_table('weather_observations')
    # ### end Alembic commands ###
