"""
Column provenance registry: where every dataset column comes from and whether the model uses it.

- real:      measured values from the public FAOSTAT / World Bank "yield_df" dataset
- synthetic: generated by scripts/preprocess_real_dataset.py to fill the schema (random, not measured)
- derived:   computed from other columns (identifiers, dates, or — for NDVI — the yield itself)
"""
from typing import Literal

Provenance = Literal["real", "synthetic", "derived"]

SOURCE_DATASET = "Kaggle “Crop Yield Prediction Dataset” (yield_df.csv), built from FAOSTAT and World Bank data"

# column -> (provenance, label, unit, origin, note)
_REGISTRY: dict[str, tuple[Provenance, str, str, str, str]] = {
    "farm_id": ("derived", "Record ID", "", "Sequential row identifier", "Not a real farm; one ID per country · crop · year row."),
    "region": ("real", "Region", "", "FAOSTAT “Area”", "Country, not a field location."),
    "crop_type": ("real", "Crop", "", "FAOSTAT “Item”", "Names normalised (e.g. “Rice, paddy” → Rice)."),
    "year": ("real", "Year", "", "FAOSTAT “Year”", "Harvest year, 1990–2013."),
    "yield_kg_per_hectare": ("real", "Yield", "kg/ha", "FAOSTAT “hg/ha_yield” ÷ 10", "National average yield: the prediction target."),
    "rainfall_mm": ("real", "Rainfall", "mm", "World Bank average annual rainfall", "Country-level long-term average: one value per country, constant across years. Its model effect is a cross-country association, not a yearly weather effect."),
    "temperature_C": ("real", "Temperature", "°C", "Average annual temperature", "Country-level annual mean."),
    "pesticide_usage_ml": ("real", "Pesticides", "index", "FAOSTAT pesticides (tonnes) × 100", "National pesticide use, scaled; not a per-field application rate."),
    "total_days": ("synthetic", "Crop duration", "days", "Per-crop typical duration ± random days", "Synthetic crop proxy: a fixed per-crop base plus ±10 random days. Not used by the model since v2.1."),
    "sowing_date": ("derived", "Sowing date", "", "Year + fixed 15 January", "Placeholder date; only the year is real."),
    "harvest_date": ("derived", "Harvest date", "", "Year + fixed 15 May", "Placeholder date; only the year is real."),
    "soil_pH": ("synthetic", "Soil pH", "pH", "Per-crop base + random noise", "Not measured. Not used by the model."),
    "soil_moisture_%": ("synthetic", "Soil moisture", "%", "Scaled rainfall + random noise", "Not measured. Not used by the model."),
    "humidity_%": ("synthetic", "Humidity", "%", "Rainfall and temperature formula + noise", "Not measured. Not used by the model."),
    "sunlight_hours": ("synthetic", "Sunlight", "h/day", "Rainfall formula + noise", "Not measured. Not used by the model."),
    "irrigation_type": ("synthetic", "Irrigation", "", "Rule on rainfall + random choice", "Not measured. Not used by the model."),
    "fertilizer_type": ("synthetic", "Fertilizer", "", "Random choice", "Not measured. Not used by the model."),
    "crop_disease_status": ("synthetic", "Disease status", "", "Random, weighted by synthetic humidity", "Not measured. Not used by the model."),
    "NDVI_index": ("derived", "NDVI", "index", "Yield percentile rank + noise", "Computed from the yield itself (target leakage). Excluded from the model; shown for reference only."),
}


def registry(model_features: list[str]) -> list[dict]:
    return [
        {
            "column": col,
            "label": label,
            "unit": unit,
            "provenance": prov,
            "origin": origin,
            "note": note,
            "used_by_model": col in model_features,
        }
        for col, (prov, label, unit, origin, note) in _REGISTRY.items()
    ]


def provenance_of(column: str) -> Provenance | None:
    entry = _REGISTRY.get(column)
    return entry[0] if entry else None
