"""
Column provenance registry: where every dataset column comes from and whether the model uses it.

- real:      measured values: FAOSTAT yields and pesticides, CRU TS country rainfall and temperature
- synthetic: generated by scripts/preprocess_real_dataset.py to fill the schema (random, not measured)
- derived:   computed from other columns (identifiers, dates, or — for NDVI — the yield itself)
"""
from typing import Literal

Provenance = Literal["real", "synthetic", "derived"]

SOURCE_DATASET = "FAOSTAT yields and pesticides with CRU TS 4.08 country rainfall and temperature (World Bank CCKP), 1990–2023 (scripts/build_dataset_v3.py)"

# column -> (provenance, label, unit, origin, note)
_REGISTRY: dict[str, tuple[Provenance, str, str, str, str]] = {
    "farm_id": ("derived", "Record ID", "", "Sequential row identifier", "Not a real farm; one ID per country · crop · year row."),
    "region": ("real", "Region", "", "FAOSTAT “Area”", "Country, not a field location."),
    "crop_type": ("real", "Crop", "", "FAOSTAT “Item”", "Names normalised (e.g. “Rice, paddy” → Rice)."),
    "year": ("real", "Year", "", "FAOSTAT “Year”", "Harvest year, 1990–2023."),
    "yield_kg_per_hectare": ("real", "Yield", "kg/ha", "FAOSTAT QCL “Yield” (kg/ha)", "National average yield: the prediction target."),
    "rainfall_mm": ("real", "Rainfall", "mm", "CRU TS 4.08 annual precipitation, country average (World Bank CCKP)", "The country's actual rainfall in that year, so it varies year to year. Country-wide, not field-level."),
    "temperature_C": ("real", "Temperature", "°C", "CRU TS 4.08 annual mean temperature, country average (World Bank CCKP)", "Country-level annual mean for that year."),
    "pesticide_usage_ml": ("real", "Pesticides", "index", "FAOSTAT Pesticides Use, total agricultural use (tonnes) × 100", "National pesticide use, scaled; not a per-field application rate."),
    "total_days": ("synthetic", "Crop duration", "days", "Per-crop typical duration ± random days", "Synthetic crop proxy: a fixed per-crop base plus ±10 random days. Not used by the model since v2.1."),
    "sowing_date": ("derived", "Sowing date", "", "Year + fixed 15 January", "Placeholder date; only the year is real."),
    "harvest_date": ("derived", "Harvest date", "", "Year + fixed 15 May", "Placeholder date; only the year is real."),
    "soil_pH": ("synthetic", "Soil pH", "pH", "Per-crop base + random noise", "Not measured. Not used by the model."),
    "soil_moisture_%": ("synthetic", "Soil moisture", "%", "Scaled rainfall + random noise", "Not measured. Not used by the model."),
    "humidity_%": ("synthetic", "Humidity", "%", "Rainfall and temperature formula + noise", "Not measured. Not used by the model."),
    "sunlight_hours": ("synthetic", "Sunlight", "h/day", "Rainfall formula + noise", "Not measured. Not used by the model."),
    "irrigation_type": ("synthetic", "Irrigation", "", "Rule on rainfall + random choice", "Not measured. Not used by the model."),
    "fertilizer_type": ("synthetic", "Fertilizer", "", "Random choice", "Not measured. Not used by the model."),
    "crop_disease_status": ("synthetic", "Disease status", "", "Random, weighted by synthetic humidity", "Not measured. Not used by the model."),
    "yield_lag1": ("derived", "Last season's yield", "kg/ha", "Real FAOSTAT yield of the previous recorded season (same country and crop)", "Known before the season starts, so it isn't leakage. Used by the model since v3.0."),
    "yield_mean3": ("derived", "3-season mean yield", "kg/ha", "Mean real FAOSTAT yield of up to 3 earlier seasons", "Known before the season starts. Used by the model since v3.0."),
    "NDVI_index": ("derived", "NDVI", "index", "Yield percentile rank + noise", "Computed from the yield itself (target leakage). Excluded from the model; shown for reference only."),
}


def registry(model_features: list[str]) -> list[dict]:
    return [
        {
            "column": col,
            "label": label,
            "unit": unit,
            "provenance": prov,
            "origin": origin,
            "note": note,
            "used_by_model": col in model_features,
        }
        for col, (prov, label, unit, origin, note) in _REGISTRY.items()
    ]


def provenance_of(column: str) -> Provenance | None:
    entry = _REGISTRY.get(column)
    return entry[0] if entry else None
